import {
  ButtonProps,
  FlatListProps,
  ImageBackgroundProps,
  ImageProps,
  ImageStyle,
  InputAccessoryViewProps,
  KeyboardAvoidingViewProps,
  OpaqueColorValue,
  PressableProps,
  ScrollViewProps,
  SectionListProps,
  TextInputProps,
  TextProps,
  TextStyle,
  TouchableHighlightProps,
  TouchableNativeFeedbackProps,
  TouchableOpacityProps,
  TouchableWithoutFeedbackProps,
  ViewProps,
  ViewStyle,
  VirtualizedListProps,
} from "react-native";
